# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install PPA
        run: sudo add-apt-repository ppa:vriviere/ppa
        
      - name: Install MiNT Cross-tools
        run: sudo apt-get install binutils-m68k-atari-mint gcc-m68k-atari-mint mintbin-m68k-atari-mint mintlib-m68k-atari-mint gemlib-m68k-atari-mint make zip
      
      - uses: actions/checkout@v2
      
      - name: Build Worm
        run: make -f makefile.gnu CC=m68k-atari-mint-gcc clean all 
