
name: Build Binary Release

on:
  release:
    types:
      - created
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install PPA
        run: sudo add-apt-repository ppa:vriviere/ppa
        
      - name: Install MiNT Cross-tools
        run: sudo apt-get install binutils-m68k-atari-mint gcc-m68k-atari-mint mintbin-m68k-atari-mint mintlib-m68k-atari-mint gemlib-m68k-atari-mint make zip
      
      - uses: actions/checkout@v2
      
      - name: Build Worm
        run: make -f makefile.gnu CC=m68k-atari-mint-gcc clean all 
        
      - name: Build Worm Zip
        run: zip -9 worm.zip worm.app wormst.rsc license.txt readme.txt

      - name: Upload Worm
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./worm.zip
          asset_name: worm.zip
          asset_content_type: application/zip
        
